[project]
name = "ulcerative-colitis"
version = "0.1.0"
authors = [{name = "Adam KukuÄka", email = "524905@muni.cz"}]
requires-python = ">=3.12,<3.13"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "torch>=2.4.0",
    "lightning>=2.4.0",
    "torchmetrics>=1.4.1",
    "torchvision>=0.17.2",
    "albumentations>=1.4.14",
    "ipykernel",
    "timm",
    "rationai-mlkit",
    "rationai-masks",
    "rationai-tiling",
]

[tool.uv]
dev-dependencies = [
    "mypy>=1.11.2",
    "pre-commit>=3.8.0",
    "ruff>=0.6.8",
]

[tool.uv.sources]
rationai-mlkit = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/mlkit.git" }
rationai-masks = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/masks.git" }
rationai-tiling = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/tiling.git" }