# @package _global_

output_dir: ${project_dir}/embeddings/${dataset.institution}/${dataset.level}/${tile_encoder.name}

dataloader:
  batch_size: 2048  # 2048 for H100, 1024 for A40, 512 for mig-2g.20gb
  num_workers: 8
  persistent_workers: True

metadata:
  run_name: 'ðŸ“‚ Embeddings: ${dataset.institution} - ${dataset.level} - ${tile_encoder.name}'
  description: Embeddings preprocessing for ${dataset.institution} institution with ${tile_encoder.name} tile encoder.
  hyperparams:
    tile_encoder: ${tile_encoder.name}
    level: ${dataset.level}
    batch_size: ${dataloader.batch_size}
    num_workers: ${dataloader.num_workers}