# @package _global_

output_dir: ${project_dir}/quality_control/${dataset.institution}

request_timeout: 18000
max_concurrent: 5

qc_parameters:
  mask_level: 3
  sample_level: 1
  check_residual: True
  check_folding: False
  check_focus: True
  wb_correction: True


metadata:
  run_name: "ðŸŽ­ QC Masks: ${dataset.institution}"
  description: Quality control masks for ${dataset.institution} institution
  hyperparams: ${qc_parameters}