# @package _global_

max_concurrent: 64
artifact_path: tile_masks

metadata:
  run_name: "ğŸ­ Tile Masks: ${dataset.institution}"
  description: Tile masks for ${dataset.institution} at level ${dataset.level}