# @package _global_

mpp: ???
tile_extent: ???
stride: ???
tissue_threshold: 0.5

splits:
  train: ???
  test_preliminary: ???
  test_final: ???

metadata:
  run_name: "ðŸ§± Tiling: ${tile_extent}"
  # run_name: "ðŸ§± Tiling: ${dataset.institution} ${tile_extent}"
  description: Tile extraction for  institution with tile extent ${tile_extent}
  # description: Tile extraction for ${dataset.institution} institution with tile extent ${tile_extent}
  hyperparams:
    mpp: ${mpp}
    tile_extent: ${tile_extent}
    stride: ${stride}
    tissue_threshold: ${tissue_threshold}
