# @package _global_

defaults:
  - dataset/processed_w_masks/knl_patos
  - _self_


mpp: 0.17
tile_extent: 430
level: 0
tiling_uris:
  test_preliminary: "mlflow-artifacts:/86/eb29255c944d4dad926160a7cb102ad9/artifacts/test preliminary - knl_patos" # TODO update URI
  test_final: "mlflow-artifacts:/86/eb29255c944d4dad926160a7cb102ad9/artifacts/test final - knl_patos" # TODO update URI