defaults:
  - /dataset/processed_w_masks/knl_patos@_here_
  - _self_

mpp: 0.52
tile_extent: 224
level: 1
uris:
  test_preliminary: "mlflow-artifacts:/86/6782155362d54ecc9f1beccb4362d359/artifacts/test preliminary - knl_patos" # TODO update URI
  test_final: "mlflow-artifacts:/86/6782155362d54ecc9f1beccb4362d359/artifacts/test final - knl_patos" # TODO update URI