# @package _global_

defaults:
  - dataset/processed_w_masks/knl_patos
  - _self_

mpp: 1.55
tile_extent: 224
level: 2
tiling_uris:
  test_preliminary: "mlflow-artifacts:/86/d7486bb6b667433989c3ce1c8ce31d60/artifacts/test preliminary - knl_patos" # TODO update URI
  test_final: "mlflow-artifacts:/86/d7486bb6b667433989c3ce1c8ce31d60/artifacts/test final - knl_patos" # TODO update URI