defaults:
  - hydra: default
  - logger: mlflow
  - /data/datasets@data.train: ulcerative_colitis/train
  - /data/datasets@data.val: ulcerative_colitis/val
  - /data/datasets@data.test: ulcerative_colitis/val  # TODO: change to test later
  - /data/datasets@data.predict: ulcerative_colitis/val  # TODO: change to predict later
  - model/backbone: vgg16
  - _self_

seed: ${random_seed:}
mode: ???
checkpoint: null

trainer:
  enable_checkpointing: True
  max_epochs: 30
  log_every_n_steps: 5
  callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      save_top_k: 1
      monitor: validation/loss
      mode: min
    - _target_: lightning.pytorch.callbacks.EarlyStopping
      monitor: validation/loss
      mode: min
      patience: 5
    - _target_: ulcerative_colitis.callbacks.MLFlowPredictionCallback

data:
  batch_size: 16
  num_workers: 4

model:
  lr: 0.001

metadata:
  experiment_name: IKEM
  run_name: 'üèãÔ∏è‚Äç‚ôÇÔ∏è Training: Ulcerative Colitis'
  description: Trail training of ulcerative colitis dataset
  user: AdamK
  hyperparams: {}
