defaults:
  - hydra: default
  - logger: mlflow
  - /data/datasets@data.train: ulcerative_colitis/train
  - /data/datasets@data.val: ulcerative_colitis/val
  - /data/datasets@data.test: ulcerative_colitis/test
  - /data/datasets@data.predict: ulcerative_colitis/predict
  - model/backbone: vgg16
  - _self_

seed: ${random_seed:}
mode: ???
checkpoint: null

trainer:
  enable_checkpointing: True
  max_epochs: 300
  log_every_n_steps: 5
  check_val_every_n_epoch: 10
  callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      save_top_k: 1
      monitor: validation/loss
      mode: min
    - _target_: lightning.pytorch.callbacks.EarlyStopping
      monitor: validation/loss
      mode: min
      patience: 5
    - _target_: ulcerative_colitis.callbacks.MaskBuilderCallback
    # - _target_: ulcerative_colitis.callbacks.MLFlowPredictionCallback

data:
  batch_size: 4
  num_workers: 4
  train:
    inner_batch_size: 32

model:
  lr: 0.00001

metadata:
  experiment_name: IKEM
  run_name: 'üèãÔ∏è‚Äç‚ôÇÔ∏è Training: Ulcerative Colitis'
  description: Trail training of ulcerative colitis dataset
  user: AdamK
  hyperparams: {}
