defaults:
  - hydra: default
  - logger: mlflow
  - /data/datasets@data.train: ulcerative_colitis/train
  - /data/datasets@data.val: ulcerative_colitis/val
  - /data/datasets@data.test: ulcerative_colitis/test
  - _self_

seed: ${random_seed:}
mode: ???
checkpoint: null

trainer:
  enable_checkpointing: True
  max_epochs: 10
  log_every_n_steps: 5
  callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      save_top_k: 1
      monitor: validation/loss
      mode: min

data:
  batch_size: 256
  num_workers: 8

model:
  backbone: vgg16

metadata:
  experiment_name: ???
  run_name: ???
  description: ???
  hyperparams: {}
