defaults:
  - hydra: default
  - logger: mlflow
  - /data/datasets@data.predict: embeddings/predict
  - _self_

seed: ${random_seed:}
mode: predict
checkpoint: ???

trainer:
  callbacks:
    - _target_: ulcerative_colitis.callbacks.OcclusionCallback
      sliding_window: 28
      stride: 14
      batch_size: 16
      color: 180

data:
  batch_size: 1
  num_workers: 4
  predict:
    mode: neutrophils
    slide_names:
      - 5005_23_HE
      - 1468_23_HE

model: {}

metadata:
  experiment_name: IKEM
  run_name: 'üó£Ô∏è Explaining: Ulcerative Colitis - Neutrophils MIL'
  description: 'Ulcerative Colitis'
  user: AdamK
  hyperparams: {}

