paths:
  base_folder: /mnt/projects/inflammatory_bowel_disease/ulcerative_colitis
  data_folder: /mnt/data

  slides:
    ikem: ${paths.data_folder}/IKEM/colon/IBD_AI/20x
    ftn: ${paths.data_folder}/FTN/colon/IBD_AI
    knl_patos: ${paths.data_folder}/KNL_PATOS/colon/IBD_AI

  datasets:
    ikem: ${paths.data_folder}/IKEM/colon/IBD_AI/20x/IBD_AI.csv
    ftn: ${paths.data_folder}/FTN/colon/IBD_AI/IBD_AI.csv
    knl_patos: ${paths.data_folder}/KNL_PATOS/colon/IBD_AI/IBD_AI.csv

  qc_masks:
    ikem: ${paths.base_folder}/qc_masks/ikem
    ftn: ${paths.base_folder}/qc_masks/ftn
    knl_patos: ${paths.base_folder}/qc_masks/knl_patos

  tissue_masks:
    ikem: ${paths.base_folder}/tissue_masks/ikem
    ftn: ${paths.base_folder}/tissue_masks/ftn
    knl_patos: ${paths.base_folder}/tissue_masks/knl_patos

  embeddings:
    "1": # level
      ikem:
        prov-gigapath: ${paths.base_folder}/embeddings/ikem/1/prov_gigapath
        virchow2: ${paths.base_folder}/embeddings/ikem/1/virchow2
        uni2: ${paths.base_folder}/embeddings/ikem/1/uni2
      ikem_old:
        prov-gigapath: ${paths.base_folder}/embeddings/ikem_old/1/prov_gigapath
        virchow2: ${paths.base_folder}/embeddings/ikem_old/1/virchow2
        uni2: ${paths.base_folder}/embeddings/ikem_old/1/uni2
        virchow: ${paths.base_folder}/embeddings/ikem_old/1/virchow
        uni: ${paths.base_folder}/embeddings/ikem_old/1/uni
      ftn:
        prov-gigapath: ${paths.base_folder}/embeddings/ftn/1/prov_gigapath
        virchow2: ${paths.base_folder}/embeddings/ftn/1/virchow2
        uni2: ${paths.base_folder}/embeddings/ftn/1/uni2
      knl_patos:
        prov-gigapath: ${paths.base_folder}/embeddings/knl_patos/1/prov_gigapath
        virchow2: ${paths.base_folder}/embeddings/knl_patos/1/virchow2
        uni2: ${paths.base_folder}/embeddings/knl_patos/1/uni2
      all:
        prov-gigapath:
          - ${...ikem.prov-gigapath}
          - ${...ftn.prov-gigapath}
          - ${...knl_patos.prov-gigapath}
        virchow2:
          - ${...ikem.virchow2}
          - ${...ftn.virchow2}
          - ${...knl_patos.virchow2}
        uni2:
          - ${...ikem.uni2}
          - ${...ftn.uni2}
          - ${...knl_patos.uni2}
    "2": # level
      ikem:
        virchow2: ${paths.base_folder}/embeddings/ikem/2/virchow2
      ftn:
        virchow2: ${paths.base_folder}/embeddings/ftn/2/virchow2
      knl_patos:
        virchow2: ${paths.base_folder}/embeddings/knl_patos/2/virchow2
      all:
        virchow2:
          - ${...ikem.virchow2}
          - ${...ftn.virchow2}
          - ${...knl_patos.virchow2}

  tile_masks:
    "1": # level
      ikem: ${paths.base_folder}/tile_masks/1/ikem
      ftn: ${paths.base_folder}/tile_masks/1/ftn
      knl_patos: ${paths.base_folder}/tile_masks/1/knl_patos
    "2": # level
      ikem: ${paths.base_folder}/tile_masks/2/ikem
      ftn: ${paths.base_folder}/tile_masks/2/ftn
      knl_patos: ${paths.base_folder}/tile_masks/2/knl_patos