paths:
  base_folder: /mnt/projects/inflammatory_bowel_dissease/ulcerative_colitis

  slides:
    ikem: ${paths.base_folder}/data_tiff/ikem
    ftn: ${paths.base_folder}/data_tiff/ftn
    knl_patos: ${paths.base_folder}/data_tiff/knl_patos

  tables:
    ikem: ${paths.base_folder}/data_czi/ikem/IBD_AI.csv
    ftn: ${paths.base_folder}/data_czi/ftn/IBD_AI.csv
    knl_patos: ???

  qc_masks:
    ikem: ${paths.base_folder}/qc_masks/ikem
    ftn: ${paths.base_folder}/qc_masks/ftn
    knl_patos: ${paths.base_folder}/qc_masks/knl_patos

  tissue_masks:
    ikem: ${paths.base_folder}/tissue_masks/ikem
    ftn: ${paths.base_folder}/tissue_masks/ftn
    knl_patos: ${paths.base_folder}/tissue_masks/knl_patos

  embeddings:
    ikem:
      prov-gigapath: ${paths.base_folder}/embeddings/ikem/prov-gigapath
      virchow2: ${paths.base_folder}/embeddings/ikem/virchow2
    ftn:
      prov-gigapath: ${paths.base_folder}/embeddings/ftn/prov-gigapath
      virchow2: ${paths.base_folder}/embeddings/ftn/virchow2
    knl_patos:
      prov-gigapath: ${paths.base_folder}/embeddings/knl_patos
      virchow2: ${paths.base_folder}/embeddings/knl_patos
    all:
      prov-gigapath:
        - ${...ikem.prov-gigapath}
        - ${...ftn.prov-gigapath}
      virchow2:
        - ${...ikem.virchow2}
        - ${...ftn.virchow2}

  tile_masks:
    ikem: ${paths.base_folder}/tile_masks/ikem
    ftn: ${paths.base_folder}/tile_masks/ftn
    knl_patos: ${paths.base_folder}/tile_masks/knl_patos