paths:
  base_folder: /mnt/projects/inflammatory_bowel_dissease/ulcerative_colitis

  slides:
    ikem: ${paths.base_folder}/data_tiff/ikem
    ftn: ${paths.base_folder}/data_tiff/ftn
    knl_patos: ${paths.base_folder}/data_tiff/knl_patos

  tables:
    ikem: ${paths.base_folder}/data_czi/ikem/IBD_AI.csv
    ftn: ${paths.base_folder}/data_czi/ftn/IBD_AI.csv
    knl_patos: ???

  qc_masks:
    ikem: ${paths.base_folder}/qc_masks/ikem
    ftn: ${paths.base_folder}/qc_masks/ftn
    knl_patos: ${paths.base_folder}/qc_masks/knl_patos

  tissue_masks:
    ikem: ${paths.base_folder}/tissue_masks/ikem
    ftn: ${paths.base_folder}/tissue_masks/ftn
    knl_patos: ${paths.base_folder}/tissue_masks/knl_patos

  embeddings:
    "0": ???
    "1": # level
      ikem:
        prov-gigapath: ${paths.base_folder}/embeddings/1/ikem/prov-gigapath
      ftn:
        prov-gigapath: ${paths.base_folder}/embeddings/1/ftn/prov-gigapath
      knl_patos:
        prov-gigapath: ${paths.base_folder}/embeddings/1/knl_patos/prov-gigapath
      all:
        prov-gigapath:
          - ${...ikem.prov-gigapath}
          - ${...ftn.prov-gigapath}
    "2": ???
    "3": # level
      ikem:
        virchow2: ${paths.base_folder}/embeddings/3/ikem/virchow2
      ftn:
        virchow2: ${paths.base_folder}/embeddings/3/ftn/virchow2
      knl_patos:
        virchow2: ${paths.base_folder}/embeddings/3/knl_patos/virchow2
      all:
        virchow2:
          - ${...ikem.virchow2}
          - ${...ftn.virchow2}
    "4": # level
      ikem:
        virchow2: ${paths.base_folder}/embeddings/4/ikem/virchow2
      ftn:
        virchow2: ${paths.base_folder}/embeddings/4/ftn/virchow2
      knl_patos:
        virchow2: ${paths.base_folder}/embeddings/4/knl_patos/virchow2
      all:
        virchow2:
          - ${...ikem.virchow2}
          - ${...ftn.virchow2}

  tile_masks:
    ikem: ${paths.base_folder}/tile_masks/ikem
    ftn: ${paths.base_folder}/tile_masks/ftn
    knl_patos: ${paths.base_folder}/tile_masks/knl_patos