defaults:
  - hydra: default
  - logger: mlflow
  - /data/datasets@data.train: neutrophils/train
  - /data/datasets@data.val: neutrophils/val
  - /data/datasets@data.test: neutrophils/test
  - /data/datasets@data.predict: neutrophils/predict
  - model/backbone: vgg16
  - _self_

seed: ${random_seed:}
mode: predict
checkpoint: ???

trainer:
  callbacks:
    - _target_: ulcerative_colitis.callbacks.MaskBuilderCallback
    - _target_: ulcerative_colitis.callbacks.MLFlowPredictionCallback

data:
  batch_size: 4
  num_workers: 4

metadata:
  experiment_name: IKEM
  run_name: 'ðŸŽ¯ Predicting: Ulcerative Colitis - Neutrophils'
  description: 'Ulcerative Colitis'
  user: AdamK
  hyperparams: {}

