defaults:
  - hydra: default
  - logger: mlflow
  - /data/datasets@data.train: embeddings/train
  - /data/datasets@data.val: embeddings/val
  - /data/datasets@data.test: embeddings/test
  - /data/datasets@data.predict: embeddings/predict
  - _self_

seed: ${random_seed:}
mode: predict
checkpoint: ???

trainer:
  callbacks:
    - _target_: ulcerative_colitis.callbacks.MaskBuilderCallback
    - _target_: ulcerative_colitis.callbacks.MLFlowPredictionCallback

data:
  batch_size: 1
  num_workers: 4

model: {}

metadata:
  experiment_name: IKEM
  run_name: 'ðŸŽ¯ Predicting: Ulcerative Colitis - Neutrophils MIL'
  description: 'Ulcerative Colitis'
  user: AdamK
  hyperparams: {}

