defaults:
  - hydra: default
  - logger: mlflow
  - _self_


paths:
  base_folder: /mnt/data/Projects/inflammatory_bowel_dissease/ulcerative_colitis

  slides:
    ikem: ${paths.base_folder}/data_tiff/ikem
    ftn: ${paths.base_folder}/data_tiff/ftn
    knl_patos: ${paths.base_folder}/data_tiff/knl_patos

  tables:
    ikem: ${paths.base_folder}/data_czi/ikem/IBD_AI.csv
    ftn: ${paths.base_folder}/data_czi/ftn/IBD_AI.csv
    knl_patos: ???

  qc_masks:
    ikem: ${paths.base_folder}/qc_masks/ikem
    ftn: ${paths.base_folder}/qc_masks/ftn
    knl_patos: ${paths.base_folder}/qc_masks/knl_patos

  tissue_masks:
    ikem: ${paths.base_folder}/tissue_masks/ikem
    ftn: ${paths.base_folder}/tissue_masks/ftn
    knl_patos: ${paths.base_folder}/tissue_masks/knl_patos

  embeddings:
    ikem:
      prov-gigapath: ${paths.base_folder}/embeddings/ikem/prov-gigapath
    ftn:
      prov-gigapath: ${paths.base_folder}/embeddings/ftn/prov-gigapath
    knl_patos:
      prov-gigapath: ${paths.base_folder}/embeddings/knl_patos
    
uris:
  qc_masks:
    ikem: "mlflow-artifacts:/86/203703bfa1c14f29874832e91b5cae32/artifacts/qc_masks"
    ftn: "mlflow-artifacts:/86/580ef09912404470abbbbae72e4b1cef/artifacts/qc_masks"
    knl_patos: ???

  tissue_masks:
    ikem: "mlflow-artifacts:/86/195d0dd68ca84fc2ad64156d10df786d/artifacts/tissue_masks"
    ftn: "mlflow-artifacts:/86/f94e472e469f4191be75e498046ab5dd/artifacts/tissue_masks"
    knl_patos: ???

  embeddings:
    ikem:
      prov-gigapath: ???
    ftn:
      prov-gigapath: ???
    knl_patos:
      prov-gigapath: ???
