defaults:
  - hydra: default
  - logger: mlflow
  - paths
  - uris
  - _self_

cohort: ???

tiling_uris: ${uris.tiling.${cohort}.all}
embeddings_uri: ${uris.embeddings.${cohort}.prov-gigapath}

embeddings_folder: ${paths.embeddings.${cohort}.prov-gigapath}
embeddings_download: True

request_limit: 10

connection_parameters:
  url: http://rayservice-models-serve-svc.rationai-jobs-ns.svc.cluster.local:8000/gigapath-slide-encoder
  request_timeout: 60 # 1 minute
  num_repeats: 3

metadata:
  experiment_name: Ulcerative Colitis
  run_name: 'ðŸ“‚ Slide Embeddings: ${cohort}'
  description: 'Ulcerative Colitis' 
  user: AdamK

