defaults:
  - hydra: default
  - logger: mlflow
  - /data/datasets@data.test: tile_embeddings/tile_embeddings
  - paths
  - uris
  - _self_

seed: ${random_seed:}
mode: test
cohort: ???
checkpoint: ???
data_mode: ???

trainer: {}

data:
  batch_size: 8
  num_workers: 4
  test:
    mode: ${data_mode}
    tiling_uri: '${uris.tiling.${cohort}}/test preliminary - ${cohort}'
    embeddings_uri: ${uris.embeddings.${cohort}.prov-gigapath}
    embeddings_folder: ${paths.embeddings.${cohort}.prov-gigapath}

model: {}

metadata:
  experiment_name: 'Ulcerative Colitis' 
  run_name: 'ğŸ“ Testing: Ulcerative Colitis - ${data_mode} ${cohort} MIL'
  description: 'Ulcerative Colitis'
  user: AdamK
  hyperparams: {}

