defaults:
  - hydra: default
  - logger: mlflow
  - /data/datasets@data.train: embeddings/train
  - /data/datasets@data.val: embeddings/val
  - /data/datasets@data.test: embeddings/test
  - /data/datasets@data.predict: embeddings/predict
  - _self_

seed: ${random_seed:}
mode: test
checkpoint: ???

trainer: {}

data:
  batch_size: 4
  num_workers: 4

model: {}

metadata:
  experiment_name: IKEM
  run_name: 'ğŸ“ Testing: Ulcerative Colitis - Embeddings'
  description: 'Ulcerative Colitis'
  user: AdamK
  hyperparams: {}

