defaults:
  - hydra: default
  - logger: mlflow
  - /data/datasets@data.test: embeddings/test
  - _self_

seed: ${random_seed:}
mode: test
checkpoint: ???

trainer: {}

data:
  batch_size: 8
  num_workers: 4
  test:
    mode: neutrophils

model: {}

metadata:
  experiment_name: IKEM
  run_name: 'ğŸ“ Testing: Ulcerative Colitis - Neutrophils MIL'
  description: 'Ulcerative Colitis'
  user: AdamK
  hyperparams: {}

