defaults:
  - hydra: default
  - logger: mlflow
  - paths
  - uris
  - _self_

cohort: ???

output_folder: ${paths.tile_masks.${cohort}}
tiling_uri: ${uris.tiling.${cohort}}

metadata:
  experiment_name: Ulcerative Colitis
  run_name: 'ðŸ“‚ Tile masks: ${cohort}'
  description: 'Ulcerative Colitis' 
  user: AdamK

