defaults:
  - hydra: default
  - logger: mlflow
  - paths
  - uris
  - _self_

cohort: ???
token: ???
model: ???
mpp: "???"

tiling_uri: ${uris.tiling.${mpp}.${cohort}.all}

output_folder: ${paths.embeddings.${cohort}.${model}}

skip_existing: False

dataloader:
  batch_size: 2048
  num_workers: 8
  persistent_workers: True

metadata:
  experiment_name: Ulcerative Colitis
  run_name: 'ðŸ“‚ Tile Embeddings: ${cohort} ${model}'
  description: 'Ulcerative Colitis' 
  user: AdamK

