defaults:
  - preprocessing
  - _self_

cohort: ???

output_folder: ${paths.tile_masks.${cohort}}
tiling_uri: ${uris.tilling.${cohort}}

metadata:
  experiment_name: Ulcerative Colitis
  run_name: 'ðŸ“‚ Tile masks: ${cohort}'
  description: 'Ulcerative Colitis' 
  user: AdamK

