defaults:
  - hydra: default
  - logger: mlflow
  - /data/datasets@data.train: embeddings/train
  - /data/datasets@data.val: embeddings/val
  - _self_

seed: ${random_seed:}
mode: fit
checkpoint: null

trainer:
  enable_checkpointing: True
  max_epochs: 300
  log_every_n_steps: 5
  callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      save_top_k: 1
      monitor: validation/loss
      mode: min
    - _target_: lightning.pytorch.callbacks.EarlyStopping
      monitor: validation/loss
      mode: min
      patience: 10 

data:
  batch_size: 8
  target_column: nancy_index
  num_workers: 4
  train:
    mode: nancy_low
  val:
    mode: nancy_low

model:
  lr: 0.00001

metadata:
  experiment_name: IKEM
  run_name: 'üèãÔ∏è‚Äç‚ôÇÔ∏è Training: Ulcerative Colitis - Nancy Low MIL'
  description: 'Ulcerative Colitis'
  user: AdamK
  hyperparams: {}

