defaults:
  - hydra: default
  - logger: mlflow
  - /data/datasets@data.train: embeddings/train
  - _self_

seed: ${random_seed:}
mode: fit
checkpoint: null

trainer:
  enable_checkpointing: True
  max_epochs: 300
  log_every_n_steps: 5
  callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      save_top_k: 1
      monitor: validation/loss
      mode: min
    - _target_: lightning.pytorch.callbacks.EarlyStopping
      monitor: validation/loss
      mode: min
      patience: 10 

data:
  batch_size: 8
  target_column: neutrophils
  num_workers: 4
  kfold_splits: 5
  k: 1
  train:
    mode: neutrophils
    minimum_region_size: 100

model:
  lr: 0.00001

metadata:
  experiment_name: IKEM
  run_name: 'üèãÔ∏è‚Äç‚ôÇÔ∏è Training: Ulcerative Colitis - Neutrophils MIL (fold ${data.k}/${data.kfold_splits})'
  description: 'Ulcerative Colitis'
  user: AdamK
  hyperparams: {}

