uris:
  qc_masks:
    ikem: "mlflow-artifacts:/86/8394e4a4992d494bbdb841e5453eeffa/artifacts/qc_masks"
    ftn: "mlflow-artifacts:/86/6e5337910f544b39ae08ab346688ef18/artifacts/qc_masks"
    knl_patos: "mlflow-artifacts:/86/5959fcfdfb8941e0a4eb07ff3c3f18c1/artifacts/qc_masks"

  tissue_masks:
    ikem: "mlflow-artifacts:/86/7b78c2c848ce4459a85f3bc9678b99ad/artifacts/tissue_masks"
    ftn: "mlflow-artifacts:/86/6b89d95195db42609a389dd4fe40cd0a/artifacts/tissue_masks"
    knl_patos: "mlflow-artifacts:/86/eec5c9f9c3cf45799ac458d28f7dc7c5/artifacts/tissue_masks"

  embeddings:
    "1": # level
      ikem:
        prov-gigapath: ???
        virchow2: ???
        uni2: ???
        virchow: ???
        uni: ???
      ikem_old: # old
        prov-gigapath: mlflow-artifacts:/86/4c19977258e4464b82d2aa5b555abf9f/artifacts/embeddings
        virchow2: mlflow-artifacts:/86/c3efe1fc08864a97ab3ca2fe0796405a/artifacts/embeddings
        uni2: mlflow-artifacts:/86/1152d6b74fae4d6d8f34438c4630e893/artifacts/embeddings
        virchow: mlflow-artifacts:/86/c4b7bcf86c174383b13cc519f580a8ad/artifacts/embeddings
        uni: mlflow-artifacts:/86/7e52fc2663754cfe91d3b37842569631/artifacts/embeddings
      ftn:
        prov-gigapath: ???
        virchow2: ???
        uni2: ???
        virchow: ???
        uni: ???
      knl_patos:
        prov-gigapath: mlflow-artifacts:/86/c8affc9b9dde4c4fa1db458631e3ac70/artifacts/embeddings
        virchow2: mlflow-artifacts:/86/3c97b1e073ba47dba90cb1fa68276001/artifacts/embeddings
        uni2: mlflow-artifacts:/86/27ca95a2c7664012bad373a972b20600/artifacts/embeddings
        virchow: ???
        uni: ???
      all:
        prov-gigapath:
          # - ${...ikem.prov-gigapath}
          # - ${...ftn.prov-gigapath}
          - ${...knl_patos.prov-gigapath}
        virchow2:
          # - ${...ikem.virchow2}
          # - ${...ftn.virchow2}
          - ${...knl_patos.virchow2}
        uni2:
          # - ${...ikem.uni2}
          # - ${...ftn.uni2}
          - ${...knl_patos.uni2}
        # virchow:
        #   - ${...ikem.virchow}
        #   - ${...ftn.virchow}
        #   - ${...knl_patos.virchow}
        # uni:
        #   - ${...ikem.uni}
        #   - ${...ftn.uni}
        #   - ${...knl_patos.uni}
    "2":
      ikem:
        virchow2: mlflow-artifacts:/86/6f723bf5adb346e0a414830cc5316663/artifacts/embeddings
      ftn:
        virchow2: mlflow-artifacts:/86/6e73dcc1841e4b8894351adbcf90c1e5/artifacts/embeddings
      knl_patos:
        virchow2: mlflow-artifacts:/86/dc430f8aa25442b0a749f4b8b54dec4b/artifacts/embeddings
      all:
        virchow2:
          - ${...ikem.virchow2}
          - ${...ftn.virchow2}
          - ${...knl_patos.virchow2}

  tiling:
    "1": # level
      ikem: 
        train: mlflow-artifacts:/86/0890e5b6e1254ee78458a1cc973f5c6c/artifacts/train - ikem
        test_preliminary: mlflow-artifacts:/86/0890e5b6e1254ee78458a1cc973f5c6c/artifacts/test preliminary - ikem
        test_final: mlflow-artifacts:/86/0890e5b6e1254ee78458a1cc973f5c6c/artifacts/test final - ikem
        all:
          - ${..train}
          - ${..test_preliminary}
          - ${..test_final}
      ikem_old: # old
        train: mlflow-artifacts:/86/113e701f7a2a428687401ed4cb0917a6/artifacts/train - ikem
        test_preliminary: mlflow-artifacts:/86/113e701f7a2a428687401ed4cb0917a6/artifacts/test preliminary - ikem
        test_final: mlflow-artifacts:/86/113e701f7a2a428687401ed4cb0917a6/artifacts/test final - ikem
        all:
          - ${..train}
          - ${..test_preliminary}
          - ${..test_final}
      ftn: 
        train: mlflow-artifacts:/86/42bab4ee199640ee8810e51f4dcbfac9/artifacts/train - ftn
        test_preliminary: mlflow-artifacts:/86/42bab4ee199640ee8810e51f4dcbfac9/artifacts/test preliminary - ftn
        test_final: mlflow-artifacts:/86/42bab4ee199640ee8810e51f4dcbfac9/artifacts/test final - ftn
        all:
          - ${..train}
          - ${..test_preliminary}
          - ${..test_final}
      knl_patos: 
        test_preliminary: mlflow-artifacts:/86/a04e4e253299459987a04d6f1751969f/artifacts/test preliminary - knl_patos
        test_final: mlflow-artifacts:/86/a04e4e253299459987a04d6f1751969f/artifacts/test final - knl_patos
        all:
          - ${..test_preliminary}
          - ${..test_final}
      all:
        train:
          - ${...ikem.train}
          - ${...ftn.train}
        test_preliminary:
          - ${...ikem.test_preliminary}
          - ${...ftn.test_preliminary}
          - ${...knl_patos.test_preliminary}
        test_final:
          - ${...ikem.test_final}
          - ${...ftn.test_final}
          - ${...knl_patos.test_final}
    "2": # level
      ikem: 
        train: mlflow-artifacts:/86/772f1a2adea543b482d3cec12700351e/artifacts/train - ikem
        test_preliminary: mlflow-artifacts:/86/772f1a2adea543b482d3cec12700351e/artifacts/test preliminary - ikem
        test_final: mlflow-artifacts:/86/772f1a2adea543b482d3cec12700351e/artifacts/test final - ikem
        all:
          - ${..train}
          - ${..test_preliminary}
          - ${..test_final}
      ftn: 
        train: mlflow-artifacts:/86/f1ff46e59ae54feb97088b4baf419330/artifacts/train - ftn
        test_preliminary: mlflow-artifacts:/86/f1ff46e59ae54feb97088b4baf419330/artifacts/test preliminary - ftn
        test_final: mlflow-artifacts:/86/f1ff46e59ae54feb97088b4baf419330/artifacts/test final - ftn
        all:
          - ${..train}
          - ${..test_preliminary}
          - ${..test_final}
      knl_patos: 
        test_preliminary: mlflow-artifacts:/86/c15d17315af64952a849b21984f728ed/artifacts/test preliminary - knl_patos
        test_final: mlflow-artifacts:/86/c15d17315af64952a849b21984f728ed/artifacts/test final - knl_patos
        all:
          - ${..test_preliminary}
          - ${..test_final}
      all:
        train:
          - ${...ikem.train}
          - ${...ftn.train}
        test_preliminary:
          - ${...ikem.test_preliminary}
          - ${...ftn.test_preliminary}
          - ${...knl_patos.test_preliminary}
        test_final:
          - ${...ikem.test_final}
          - ${...ftn.test_final}
          - ${...knl_patos.test_final}
