uris:
  qc_masks:
    ikem: "mlflow-artifacts:/86/203703bfa1c14f29874832e91b5cae32/artifacts/qc_masks"
    ftn: "mlflow-artifacts:/86/580ef09912404470abbbbae72e4b1cef/artifacts/qc_masks"
    knl_patos: ???

  tissue_masks:
    ikem: "mlflow-artifacts:/86/195d0dd68ca84fc2ad64156d10df786d/artifacts/tissue_masks"
    ftn: "mlflow-artifacts:/86/f94e472e469f4191be75e498046ab5dd/artifacts/tissue_masks"
    knl_patos: ???

  embeddings:
    ikem:
      prov-gigapath: "mlflow-artifacts:/86/d6346f4504dd4f3da92fc6080df3db81/artifacts/embeddings"
    ftn:
      prov-gigapath: "mlflow-artifacts:/86/5ad6eb380be14a259bb59b190a66e8bb/artifacts/embeddings"
    knl_patos:
      prov-gigapath: ???

  slide_embeddings:
    ikem: "mlflow-artifacts:/86/95d8e3bd07da4755acaf435082fd538f/artifacts"
    ftn: "mlflow-artifacts:/86/95d8e3bd07da4755acaf435082fd538f/artifacts"
    knl_patos: ???
    all:
      - ${uris.slide_embeddings.ikem}
      - ${uris.slide_embeddings.ftn}

  tiling:
    ikem: 
      train: "mlflow-artifacts:/86/c21ea1955fd44365af32fa773fb25bcd/artifacts/train - ikem"
      test_preliminary: "mlflow-artifacts:/86/c21ea1955fd44365af32fa773fb25bcd/artifacts/test preliminary - ikem"
      test_final: "mlflow-artifacts:/86/c21ea1955fd44365af32fa773fb25bcd/artifacts/test final - ikem"
      all:
        - ${uris.tiling.ikem.train}
        - ${uris.tiling.ikem.test_preliminary}
        - ${uris.tiling.ikem.test_final}
    ftn: 
      train: "mlflow-artifacts:/86/28e6b60b4eb64e01b37e947869ac1f85/artifacts/train - ftn"
      test_preliminary: "mlflow-artifacts:/86/28e6b60b4eb64e01b37e947869ac1f85/artifacts/test preliminary - ftn"
      test_final: "mlflow-artifacts:/86/28e6b60b4eb64e01b37e947869ac1f85/artifacts/test final - ftn"
      all:
        - ${uris.tiling.ftn.train}
        - ${uris.tiling.ftn.test_preliminary}
        - ${uris.tiling.ftn.test_final}
    knl_patos: 
      train: ???
      test_preliminary: ???
      test_final: ???
    all:
      train:
        - ${uris.tiling.ikem.train}
        - ${uris.tiling.ftn.train}
      test preliminary:
        - ${uris.tiling.ikem.test_preliminary}
        - ${uris.tiling.ftn.test_preliminary}
      test final:
        - ${uris.tiling.ikem.test_final}
        - ${uris.tiling.ftn.test_final}
