uris:
  qc_masks:
    ikem: "mlflow-artifacts:/86/203703bfa1c14f29874832e91b5cae32/artifacts/qc_masks"
    ftn: "mlflow-artifacts:/86/580ef09912404470abbbbae72e4b1cef/artifacts/qc_masks"
    knl_patos: ???

  tissue_masks:
    ikem: "mlflow-artifacts:/86/195d0dd68ca84fc2ad64156d10df786d/artifacts/tissue_masks"
    ftn: "mlflow-artifacts:/86/f94e472e469f4191be75e498046ab5dd/artifacts/tissue_masks"
    knl_patos: ???

  embeddings:
    ikem:
      prov-gigapath: "mlflow-artifacts:/86/d6346f4504dd4f3da92fc6080df3db81/artifacts/embeddings"
      virchow2: "mlflow-artifacts:/86/4732d3b8074646a0b9f8ebdfc9dc9254/artifacts/embeddings"
    ftn:
      prov-gigapath: "mlflow-artifacts:/86/5ad6eb380be14a259bb59b190a66e8bb/artifacts/embeddings"
      virchow2: "mlflow-artifacts:/86/ecc4d7b2093d44fc9aa48e30ef0675c8/artifacts/embeddings"
    knl_patos:
      prov-gigapath: ???
      virchow2: ???
    all:
      prov-gigapath:
        - ${...ikem.prov-gigapath}
        - ${...ftn.prov-gigapath}
      virchow2:
        - ${...ikem.virchow2}
        - ${...ftn.virchow2}

  slide_embeddings:
    ikem: "mlflow-artifacts:/86/372f293bccd442dcb0a72bfcccac7f07/artifacts/slide_embeddings"
    ftn: "mlflow-artifacts:/86/97cd2949f0054ecbac7c0a8dcc2e3c9f/artifacts/slide_embeddings"
    knl_patos: ???
    all:
      - ${..ikem}
      - ${..ftn}

  tiling:
    "1":  # level
      ikem: 
        train: "mlflow-artifacts:/86/c21ea1955fd44365af32fa773fb25bcd/artifacts/train - ikem"
        test_preliminary: "mlflow-artifacts:/86/c21ea1955fd44365af32fa773fb25bcd/artifacts/test preliminary - ikem"
        test_final: "mlflow-artifacts:/86/c21ea1955fd44365af32fa773fb25bcd/artifacts/test final - ikem"
        all:
          - ${..train}
          - ${..test_preliminary}
          - ${..test_final}
      ftn: 
        train: "mlflow-artifacts:/86/28e6b60b4eb64e01b37e947869ac1f85/artifacts/train - ftn"
        test_preliminary: "mlflow-artifacts:/86/28e6b60b4eb64e01b37e947869ac1f85/artifacts/test preliminary - ftn"
        test_final: "mlflow-artifacts:/86/28e6b60b4eb64e01b37e947869ac1f85/artifacts/test final - ftn"
        all:
          - ${..train}
          - ${..test_preliminary}
          - ${..test_final}
      knl_patos: 
        train: ???
        test_preliminary: ???
        test_final: ???
        # all:
        #   - ${..train}
        #   - ${..test_preliminary}
        #   - ${..test_final}
      all:
        train:
          - ${...ikem.train}
          - ${...ftn.train}
        test preliminary:
          - ${...ikem.test_preliminary}
          - ${...ftn.test_preliminary}
        test final:
          - ${...ikem.test_final}
          - ${...ftn.test_final}
    "3":  # level
      ikem: 
        train: mlflow-artifacts:/86/36ccc89b303649898f83bd34d29125c7/artifacts/train - ikem
        test_preliminary: mlflow-artifacts:/86/36ccc89b303649898f83bd34d29125c7/artifacts/test preliminary - ikem
        test_final: mlflow-artifacts:/86/36ccc89b303649898f83bd34d29125c7/artifacts/test final - ikem
        all:
          - ${..train}
          - ${..test_preliminary}
          - ${..test_final}
      ftn: 
        train: mlflow-artifacts:/86/4e595c227bd64fa6a42d91f86211fb5e/artifacts/train - ftn
        test_preliminary: mlflow-artifacts:/86/4e595c227bd64fa6a42d91f86211fb5e/artifacts/test preliminary - ftn
        test_final: mlflow-artifacts:/86/4e595c227bd64fa6a42d91f86211fb5e/artifacts/test final - ftn
        all:
          - ${..train}
          - ${..test_preliminary}
          - ${..test_final}
      knl_patos: 
        train: ???
        test_preliminary: ???
        test_final: ???
        # all:
        #   - ${..train}
        #   - ${..test_preliminary}
        #   - ${..test_final}
      all:
        train:
          - ${...ikem.train}
          - ${...ftn.train}
        test preliminary:
          - ${...ikem.test_preliminary}
          - ${...ftn.test_preliminary}
        test final:
          - ${...ikem.test_final}
          - ${...ftn.test_final}
