uris:
  qc_masks:
    ikem: "mlflow-artifacts:/86/8394e4a4992d494bbdb841e5453eeffa/artifacts/qc_masks"
    ftn: "mlflow-artifacts:/86/6e5337910f544b39ae08ab346688ef18/artifacts/qc_masks"
    knl_patos: "mlflow-artifacts:/86/5959fcfdfb8941e0a4eb07ff3c3f18c1/artifacts/qc_masks"

  tissue_masks:
    ikem: "mlflow-artifacts:/86/7b78c2c848ce4459a85f3bc9678b99ad/artifacts/tissue_masks"
    ftn: "mlflow-artifacts:/86/6b89d95195db42609a389dd4fe40cd0a/artifacts/tissue_masks"
    knl_patos: "mlflow-artifacts:/86/eec5c9f9c3cf45799ac458d28f7dc7c5/artifacts/tissue_masks"

  # embeddings:
  #   "1": # level
  #     ikem:
  #       prov-gigapath: ???
  #       virchow2: ???
  #     ftn:
  #       prov-gigapath: ???
  #       virchow2: ???
  #     knl_patos:
  #       prov-gigapath: ???
  #       virchow2: ???
  #     all:
  #       prov-gigapath:
  #         - ${...ikem.prov-gigapath}
  #         - ${...ftn.prov-gigapath}
  #         - ${...knl_patos.prov-gigapath}
  #       virchow2:
  #         - ${...ikem.virchow2}
  #         - ${...ftn.virchow2}
  #         - ${...knl_patos.virchow2}
  #   "2":
  #     ikem:
  #       virchow2: ???
  #     ftn:
  #       virchow2: ???
  #     knl_patos:
  #       virchow2: ???
  #     all:
  #       virchow2:
  #         - ${...ikem.virchow2}
  #         - ${...ftn.virchow2}
  #         - ${...knl_patos.virchow2}

  # slide_embeddings:
  #   ikem: "mlflow-artifacts:/86/372f293bccd442dcb0a72bfcccac7f07/artifacts/slide_embeddings"
  #   ftn: "mlflow-artifacts:/86/97cd2949f0054ecbac7c0a8dcc2e3c9f/artifacts/slide_embeddings"
  #   knl_patos: ???
  #   all:
  #     - ${..ikem}
  #     - ${..ftn}

  tiling:
    "1": # level
      ikem: 
        train: mlflow-artifacts:/86/bd1530a4cb01496da055f2a66261ae7a/artifacts/train - ikem
        test_preliminary: mlflow-artifacts:/86/bd1530a4cb01496da055f2a66261ae7a/artifacts/test preliminary - ikem
        test_final: mlflow-artifacts:/86/bd1530a4cb01496da055f2a66261ae7a/artifacts/test final - ikem
        all:
          - ${..train}
          - ${..test_preliminary}
          - ${..test_final}
      ftn: 
        train: mlflow-artifacts:/86/eff5dd37dbc843698308088ea361eaf0/artifacts/train - ftn
        test_preliminary: mlflow-artifacts:/86/eff5dd37dbc843698308088ea361eaf0/artifacts/test preliminary - ftn
        test_final: mlflow-artifacts:/86/eff5dd37dbc843698308088ea361eaf0/artifacts/test final - ftn
        all:
          - ${..train}
          - ${..test_preliminary}
          - ${..test_final}
      knl_patos: 
        test_preliminary: mlflow-artifacts:/86/98455bf2ecb046ad994bc70e4b080187/artifacts/test preliminary - knl_patos
        test_final: mlflow-artifacts:/86/98455bf2ecb046ad994bc70e4b080187/artifacts/test final - knl_patos
        all:
          - ${..test_preliminary}
          - ${..test_final}
      all:
        train:
          - ${...ikem.train}
          - ${...ftn.train}
        test preliminary:
          - ${...ikem.test_preliminary}
          - ${...ftn.test_preliminary}
          - ${...knl_patos.test_preliminary}
        test final:
          - ${...ikem.test_final}
          - ${...ftn.test_final}
          - ${...knl_patos.test_final}
    "2": # level
      ikem: 
        train: mlflow-artifacts:/86/847946ac5a88451885b0d35fe48ee2e2/artifacts/train - ikem
        test_preliminary: mlflow-artifacts:/86/847946ac5a88451885b0d35fe48ee2e2/artifacts/test preliminary - ikem
        test_final: mlflow-artifacts:/86/847946ac5a88451885b0d35fe48ee2e2/artifacts/test final - ikem
        all:
          - ${..train}
          - ${..test_preliminary}
          - ${..test_final}
      ftn: 
        train: mlflow-artifacts:/86/812db62a640347b2ac21e5949e35dc84/artifacts/train - ftn
        test_preliminary: mlflow-artifacts:/86/812db62a640347b2ac21e5949e35dc84/artifacts/test preliminary - ftn
        test_final: mlflow-artifacts:/86/812db62a640347b2ac21e5949e35dc84/artifacts/test final - ftn
        all:
          - ${..train}
          - ${..test_preliminary}
          - ${..test_final}
      knl_patos: 
        test_preliminary: mlflow-artifacts:/86/81c63863a2b04ae383632d93c3b25b8c/artifacts/test preliminary - knl_patos
        test_final: mlflow-artifacts:/86/81c63863a2b04ae383632d93c3b25b8c/artifacts/test final - knl_patos
        all:
          - ${..test_preliminary}
          - ${..test_final}
      all:
        train:
          - ${...ikem.train}
          - ${...ftn.train}
        test preliminary:
          - ${...ikem.test_preliminary}
          - ${...ftn.test_preliminary}
          - ${...knl_patos.test_preliminary}
        test final:
          - ${...ikem.test_final}
          - ${...ftn.test_final}
          - ${...knl_patos.test_final}
