# @package _global_

defaults:
  - /dataset/processed_w_masks/ftn
  - _self_

mpp: 1.55
tile_extent: 224
level: 2
tiling_uris:
  train: "mlflow-artifacts:/86/5814484b6cd7467e9d712889655479af/artifacts/train - ftn" # TODO update URI
  test_preliminary: "mlflow-artifacts:/86/5814484b6cd7467e9d712889655479af/artifacts/test preliminary - ftn" # TODO update URI
  test_final: "mlflow-artifacts:/86/5814484b6cd7467e9d712889655479af/artifacts/test final - ftn" # TODO update URI